# Generated by Django 4.2.2 on 2023-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=500)),
                ('DateOfRegistration', models.DateField()),
                ('RegistrationNumber', models.CharField(max_length=20)),
                ('CompanyAddress', models.CharField(max_length=500)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ListofDepartments', models.CharField(max_length=700)),
                ('EmployeeNumber', models.IntegerField(max_length=1000)),
                ('Phone', models.IntegerField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=500)),
                ('EmployeeRole', models.CharField(max_length=500)),
                ('DateStarted', models.DateField()),
                ('DateLeft', models.DateField()),
                ('RoleDuties', models.CharField(max_length=500)),
            ],
        ),
    ]
